In [1]:
%load_ext autoreload
%autoreload 2
%load_ext line_profiler

In [2]:
%pwd
%cd ../..
%pwd

/Users/rgaudel/Desktop/louis_vuitton/code/bandits-to-rank


'/Users/rgaudel/Desktop/louis_vuitton/code/bandits-to-rank'

In [8]:
import numpy as np

from bandits_to_rank.sampling.pbm_inference import EM, SVD
from bandits_to_rank.opponents import Random
from bandits_to_rank.environment import Environment_PBM

# Recover parameters with uniform random samples
Not so much effivcient...

In [30]:
def simule_log_Pyclick(pbm_model, nb_sessions, thetas, kappas):
    nb_positions = len(kappas)
    nb_items = len(thetas)
    player = Random(nb_items, nb_positions)
    env = Environment_PBM(thetas, kappas)

    for t in range(nb_sessions) :
        propositions = player.choose_next_arm()
        rewards = env.get_reward(propositions)
        pbm_model.add_session(propositions,rewards)


In [31]:
thetas = [0.5, 0.7 ,0.2 ,0.8]
kappas = [1, 0.5, 0.7]
for nb_sessions in  [100, 1000, 10000]:
    print("with", nb_sessions, "sessions")
    pbm_model = EM(len(thetas), len(kappas))
    simule_log_Pyclick(pbm_model, nb_sessions, thetas, kappas)
    pbm_model.learn()
    thetas_hat, kappas_hat = pbm_model.get_params()
    print(np.sqrt(((thetas-thetas_hat)**2).mean()))
    print(thetas-thetas_hat)
    print(np.sqrt(((kappas-kappas_hat)**2).mean()))
    print(kappas-kappas_hat)
      

with 100 sessions
0.0951544524066649
[-0.15498712  0.01210904  0.1085692   0.0162041 ]
0.1437274069110525
[ 0.22822196 -0.07040458  0.07021846]
with 1000 sessions
0.08542413704145142
[-0.09486965 -0.11113473 -0.02878172 -0.08372315]
0.0862801145127856
[0.11099247 0.02850564 0.09592119]
with 10000 sessions
0.08067453565768616
[-0.07018095 -0.10585344 -0.03608204 -0.09274315]
0.08944099853309981
[0.11586592 0.06271906 0.08148917]


# Comparison to SVD approach
Là ça fonctionne !
(et rapidement .. sur de si petites matrices ...) 

In [32]:
thetas = [0.5, 0.7 ,0.2 ,0.8]
kappas = [1, 0.5, 0.7]
for nb_sessions in  [100, 1000, 10000, 100000]:
    print("with", nb_sessions, "sessions")
    pbm_model = SVD(len(thetas), len(kappas))
    simule_log_Pyclick(pbm_model, nb_sessions, thetas, kappas)
    pbm_model.learn()
    thetas_hat, kappas_hat = pbm_model.get_params()
    print(np.sqrt(((thetas-thetas_hat)**2).mean()))
    print(thetas-thetas_hat)
    print(np.sqrt(((kappas-kappas_hat)**2).mean()))
    print(kappas-kappas_hat)     

with 100 sessions
0.05149181027291929
[-0.05529229 -0.04010193 -0.0424949   0.06429936]
0.0869892016540758
[ 0.         -0.14964068 -0.01757922]
with 1000 sessions
0.033420490471547576
[ 0.05283135  0.03645452 -0.00874498  0.01646688]
0.02628302046303746
[ 0.         -0.04008627 -0.02157503]
with 10000 sessions
0.0074380301406347625
[-0.00264484 -0.01181089  0.00454966  0.00735565]
0.00968827921053264
[0.         0.00466221 0.01611993]
with 100000 sessions
0.002552579937561695
[-0.00421433  0.00200655  0.00150588 -0.0014171 ]
0.0017091958861341781
[0.         0.00046757 0.00292326]


In [33]:
thetas = [0.5, 0.7 ,0.2 ,0.8 ,0.1, 0.5, 0.7 ,0.2 ,0.8 ,0.1 ]
kappas = [1, 0.5, 0.2, 0.9, 0.7]
for nb_sessions in  [100, 1000, 10000, 100000]:
    print("with", nb_sessions, "sessions")
    pbm_model = SVD(len(thetas), len(kappas))
    simule_log_Pyclick(pbm_model, nb_sessions, thetas, kappas)
    pbm_model.learn()
    thetas_hat, kappas_hat = pbm_model.get_params()
    print(np.sqrt(((thetas-thetas_hat)**2).mean()))
    print(thetas-thetas_hat)
    print(np.sqrt(((kappas-kappas_hat)**2).mean()))
    print(kappas-kappas_hat)     

with 100 sessions
0.08924014192654435
[ 0.10420013  0.17288257 -0.01407204  0.10562703 -0.09895308  0.00611214
  0.0406113  -0.11336569  0.00306192 -0.05654543]
0.04285499025710726
[ 0.          0.0392778   0.06154771 -0.02641975 -0.05615943]
with 1000 sessions
0.02414870059384662
[ 0.00634012 -0.0162389  -0.01309578  0.02894184  0.03008833  0.04868902
 -0.01548371 -0.02468001  0.01693392  0.01034578]
0.03740151466660049
[ 0.          0.00248327 -0.0297299  -0.06316568 -0.04598293]
with 10000 sessions
0.010776635090419574
[ 0.0125705   0.00692712 -0.00405881 -0.00507275  0.00129566 -0.00734931
 -0.00424747 -0.00048515  0.028735    0.00367175]
0.012020943556492603
[ 0.          0.00571233 -0.01191441 -0.01934221 -0.01318371]
with 100000 sessions
0.0027457198495787712
[-0.00114878  0.00431639  0.00088367 -0.00567141 -0.00095722  0.00283968
  0.00118336  0.00262476 -0.0017386   0.00148345]
0.002954001371238753
[ 0.          0.00021446 -0.00305494 -0.00557252 -0.00178858]
